const InvoicesActionTypes = {
  FETCH_INVOICES_START: 'FETCH_INVOICES_START',
  FETCH_INVOICES_SUCCESS: 'FETCH_INVOICES_SUCCESS',
  FETCH_INVOICES_FAILURE: 'FETCH_INVOICES_FAILURE',
  SUBMIT_NEW_INVOICE: 'SUBMIT_NEW_INVOICE',
  DELETE_INVOICE: 'DELETE_INVOICE',
  EDIT_INVOICE: 'EDIT_INVOICE'
};

export default InvoicesActionTypes;
