const InvoiceDetailsActionTypes = {
  FETCH_INVOICES_DETAILS_START: 'FETCH_INVOICES_DETAILS_START',
  FETCH_INVOICES_DETAILS_SUCCESS: 'FETCH_INVOICES_DETAILS_SUCCESS',
  FETCH_INVOICES_DETAILS_FAILURE: 'FETCH_INVOICES_DETAILS_FAILURE',
  MARK_INVOICE_AS_PAID: 'MARK_INVOICE_AS_PAID'
};

export default InvoiceDetailsActionTypes;
